### ISSUE TITLE
Mongrel Temorary file leakage

### ISSUE THREAD

**Issue by amittomer25** [evan/mongrel#11]
Hii all,

mongrel1.1.2
ruby 1.8.6
apche 2.2.16

i am running Apche frontend to mongrel and  trying to upload some large
file(from rails application) to filesystem.Few things i observed.

1 - The uploaded data is stored in a file "mongrel.4124.0"(temporary file)
2 - the mongrel file is copied to a CGI.4124.0 file (I suppose this is
the regular Ruby tempfile)
3 - the tempfile is copied to the right location where we mention in
code.

so now what happening is after few seconds CGI.4124.0 is being deleted(may garbaselly collected) but mongrel temp file is still there holding disk space .Now i again upload same file same things happen again ,Now i have 2 mongrel temp files and 1 CGI  temp fle AFTER few seconds mongrel.4124.0 and cgi file is deleted but mongerl.4124.1 file is still there again eating disk space.

Afer that i seen mongrel http_request.rb and found Temporary file is not closed any where after use, then  I  try to do @body.close something like in order to delete mongrel temp file...but could n't do so..  
this is line where Temporary file is created

<pre><code>@body = Tempfile.new(Const::MONGREL_TMP_BASE)</code></pre>

but this is not closed any where and due to it mongrel temp file is not deleted after use

edit: big code removed, please link to the code using Source, not pasting in the bug report.

**Comment by luislavena** [comment]
Thank you for your report.

Please see my edit. Point to code in the repository instead of pasting in the bug reports. A handy tip: read GitHub Flavored Markdown documentation to avoid formatting issues.

**Comment by amittomer25** [comment]
Sorry luis i don't know how to do that Sorry

**Comment by luislavena** [comment]
This is code for controller where to upload large file

http://gist.github.com/615092

Temporary file is being generated in windows temporary folder ,you can access this is temp folder by typing `%temp%` in windows run box and one thing my application is running on windows

**Comment by luislavena** [comment]
First,

You're using ActiveRecord to save your data file at the class level, that plain suck (and no, I don't plan to explain how to do it right)

Going to see the leake of Tempfiles with a real working code, your provided one is not good.

Still, seems a valid bug report.

PS: Use gist for the code, as I did, removed your comment because it break the whole bug report.

**Comment by amittomer25** [comment]
Luis what else have to give to make it valid bug report

**Comment by luislavena** [comment]
The bug is valid, your code is not a good proof of testing validity.

Will investigate it this weekend.

**Comment by amittomer25** [comment]
Thanks luis for your response
did you get the model file where am doing upload and am also getting this problem
with my application also but  for some reason i cann't paste it and  in my application also same thing am using to upload as am doing in above code(code given here).

**Comment by luislavena** [comment]
See above gist, got your code, now you should be researching too. Is weird you're the first one having this problem in so many years, so must be something in your code.

Try different applications or approaches, even a clean application and see if this is replicable.

**Comment by amittomer25** [comment]
yaa luis i tried with different applications but the problem is still there....
and also with basic code that do the upload but still getting same result...
please whenever you have time look into this problem..

Thanks...

**Comment by amittomer25** [comment]
Hello luis,
                Are you going to verify it toaday??

**Comment by amittomer25** [comment]
Hello Luis, 
             Could i get your attention please???

**Comment by luislavena** [comment]
Amit,

First, been pushy will not receive positive answers from anyone.

Second, I can now 100 percent tell you this is not a bug, and you're doing it wrong.

Your code is leaking.

The Tempfile is never freed by you, is not Mongrel responsibility. I'm unsure which version of Rails are you using, but in my test with Rails 2.3.5 and Mongrel master branch, I was not able to get the CGI duplicates you're mentioning.

Even more, all my temporary files are RackMultipart, which indicates is using Rack (expected).

This is my model code:

http://gist.github.com/621665

After saving a new record, both the file I'm copying and the temporary file remains.

Now, if I add `GC.start` at the last sentence, the temporary file is gone because no reference is held to the Tempfile and Ruby's garbage collector can recycle the no longer used object.

I'm not here to teach you how to code, so please learn how Ruby works and don't expect others solve your problems.

I've tried been very patient with your case but your attitude went from someone that needed a hand to a help sucking vampire:

http://slash7.com/2006/12/22/vampires/

Please read a Rails programming book or use a file processing plugin/gem. Not going to answer any other personal email you send.

**Comment by amittomer25** [comment]
yaa sure luis ...
Thanks for your help and am not going to ask anymore promise...
and how i solved this problem is i closed the mongrel temp files that is not not closed in Mongrel http_request.rb ...

Gdbye
